### ISSUE TITLE
Error When Using STOIQONewRealityFLUXSD_F1DAlpha.safetensors: Empty Sequence in analyze_checkpoint_state

### ISSUE THREAD

**Issue by Siavee-uni** [cocktailpeanut/fluxgym#191]
# Error When Using `STOIQONewRealityFLUXSD_F1DAlpha.safetensors`: Empty Sequence in `analyze_checkpoint_state`

## Description:

Hello,

I'm encountering an issue when trying to train a model using the `STOIQONewRealityFLUXSD_F1DAlpha.safetensors` file from the `TheImposterImposters/STOIQONewRealityFLUXSDXLLightning-F.1DAlpha` repository.

### Steps to Reproduce:
1. Configuring the model with the following:
   ```yaml
   newReality:
       repo: TheImposterImposters/STOIQONewRealityFLUXSDXLLightning-F.1DAlpha
       base: TheImposterImposters/STOIQONewRealityFLUXSDXLLightning-F.1DAlpha
       license: other
       file: STOIQONewrealityFLUXSD_F1DAlpha.safetensors




The model is successfully downloaded, but when running the training script, I encounter the following error:

```
ValueError: max() arg is an empty sequence
```
Specifically, this occurs in the flux_utils.analyze_checkpoint_state function at line 81.

```
[INFO] _, is_schnell, _, _ = flux_utils.analyze_checkpoint_state(args.pretrained_model_name_or_path)
[INFO] File "C:\Users\Gabriel\PhpstormProjects\fluxgym\sd-scripts\library\flux_utils.py", line 81, in analyze_checkpoint_state
[INFO] max_double_block_index = max(
[INFO] ValueError: max() arg is an empty sequence
```

## Observations:

- It seems that `analyze_checkpoint_state` is attempting to calculate the `max()` value from an empty sequence, potentially due to the model checkpoint file being improperly loaded or missing certain data.
- When inspecting the state dict of the downloaded model, it seems to be missing certain keys, or the file format may not be compatible.

## Questions:

1. What changes or configuration adjustments should I make to resolve this issue? Is this a known issue with the model checkpoint format, or is the model missing some necessary metadata?
2. Is the `STOIQONewRealityFLUXSD_F1DAlpha.safetensors` file fully compatible with `flux_train_network.py`, or does it require additional steps to load properly?
3. Could you provide guidance on how to debug this further, especially regarding the empty sequence in `analyze_checkpoint_state`?
   
I’ve also checked the paths and verified that all required files (`clip_l.safetensors`, `t5xxl_fp16.safetensors`, and `ae.sft`) are correctly set up.

Any help would be greatly appreciated. Thank you in advance!
