### ISSUE TITLE
Output Doesn't Match My Training Set

### ISSUE THREAD

**Issue by LeonRui** [cocktailpeanut/fluxgym#327]
Hello, I am experiencing an issue while training Lora using FluxGym. The outputs generated from the training do not align with the data in my training set at all. The model seems to produce results that are completely unrelated to the input I provided.

Steps to Reproduce:

Load my training dataset into FluxGym.
Start training the Lora model.
Monitor the output generated after training.

![Image](https://github.com/user-attachments/assets/4221c093-2915-4942-8867-e8a85363128a)
![Image](https://github.com/user-attachments/assets/13c7484f-5b4c-4f91-acca-360ac102f9da)
![Image](https://github.com/user-attachments/assets/4db17816-4620-4f49-8c7d-6e958f9e4bd0)

As you can see, I’m training a Lora model for a cup, but the sample output gave me two people instead. I’m really confused—did I do something wrong?
Who can help me? I've been struggling with this issue for days. I'd really appreciate any help!!!

**Comment by CaledoniaProject** [comment]
兄弟，你这个提问写的太简单了。你至少得把prompt贴上去，而且你截屏的地方python都崩溃了，你不是应该先解决这个exception吗？

**Comment by LeonRui** [comment]
> 兄弟，你这个提问写的太简单了。你至少得把prompt贴上去，而且你截屏的地方python都崩溃了，你不是应该先解决这个exception吗？

这个报错是我ctrl+c 主动停止产生的，提示词就是beizi，fluxgym会直接用你的触发词，在运行到几百步之后输出触发词的sample 图片，也就相当于调用这个lora 输入触发词生成的图片。
我在想是不是不能用白底图，或者是因为我的图片训练了很多次导致的过拟合

**Comment by CaledoniaProject** [comment]
我感觉还是你的prompt没有提示词导致的，你用的啥prompt？

**Comment by LeonRui** [comment]
> 我感觉还是你的prompt没有提示词导致的，你用的啥prompt？

就直接用触发词beizi。你们平时训练lora会用白底图吗，还是用带背景的图片，还是直接扣个主体的png

**Comment by LeonRui** [comment]
> 我感觉还是你的prompt没有提示词导致的，你用的啥prompt？

好的确实是prompt的问题，prompt我只用了一个触发词，但是flux的Lora只用触发词不行，还得带上其他的描述，这好麻烦

**Comment by remoteassist** [comment]
You shouldn't you a trigger word that  is a real word, try a trigger word like "cu1p" or "beiz1"

![Image](https://github.com/user-attachments/assets/476a259c-e64f-489f-8ee9-442ef2743bd4)

**Comment by LeonRui** [comment]
> You shouldn't use a trigger word that is a real word, try a trigger word like "cu1p" or "beiz1"
> 
> ![Image](https://github.com/user-attachments/assets/476a259c-e64f-489f-8ee9-442ef2743bd4)

Yes, for Flux LoRA, it seems that a single trigger word is not enough.

**Comment by b-fission** [comment]
It should be possible to do it using `beizi cup` as the trigger word.

I trained a flux lora using kohya_ss with photos of a cup from a certain fast-food place. Only with simple captions like `closeup photo of a beizi cup filled with green liquid which sits on a tile floor.`

![Image](https://github.com/user-attachments/assets/560dea1d-24f6-4998-a3ca-e00e19e993b8)

Notice the lora strength I'm using is 1.7 which is fairly high to get a working result. My lora was trained with a text encoder (CLIP) enabled which may have helped with the trigger word.
<details>
<summary>Training config</summary>

```toml
ae = "/home/working/model/flux1DevVAE_stock.safetensors"
apply_t5_attn_mask = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
caption_extension = ".txt"
clip_l = "/home/working/model/clip_l.safetensors"
discrete_flow_shift = 3.0
dynamo_backend = "no"
enable_bucket = true
epoch = 1
fp8_base_unet = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1.0
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
logging_dir = "/home/working/tmp/model1/log"
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_train_steps = 500
min_bucket_reso = 256
min_snr_gamma = 5
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 32
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all",]
network_dim = 32
network_module = "networks.lora_flux"
noise_offset = 0.05
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "AdamW8bit"
output_dir = "/home/working/tmp/model1"
output_name = "tbellcup"
pretrained_model_name_or_path = "/home/working/COMPONENT/flux1DevFp8_v10.safetensors"
prior_loss_weight = 1
resolution = "768,768"
sample_prompts = "/home/working/tmp/model1/sample/prompt.txt"
sample_sampler = "euler"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"
sdpa = true
seed = 42
t5xxl = "/home/working/model/t5xxl_fp16.safetensors"
t5xxl_max_token_length = 512
text_encoder_lr = [ 1e-5, 1e-5,]
timestep_sampling = "sigmoid"
train_batch_size = 2
train_data_dir = "/home/working/CUP/img"
unet_lr = 0.0004
wandb_run_name = "tbellcup"

```

</details>
